pull_request_rules:
  - name: Convert wip to draft PR
    conditions:
      - label=wip
    actions:
      edit:
        draft: true
      label:
        remove:
          - wip
  - name: Make sure PR are up to date before merging with rebase
    conditions: []
    actions:
      rebase:
  - name: Owner
    description: automatically owner pr when ci passed
    conditions:
      - author = kamontat
      - check-success = main
    actions:
      merge:
  - name: Owner bot
    description: automatically merge bot pr when not autorelease
    conditions:
      - author = kc-bot
      - author = dependabot[bot]
      - check-success = main
      - "label != autorelease: pending"
    actions:
      merge:
  - name: Release bot
    description: automatically merge release pr when got approved by owner
    conditions:
      - "label = autorelease: pending"
      - approved-reviews-by = kamontat
    actions:
      merge:
