name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    default: "World"

outputs:
  matrix:
    description: "Generated strategy.matrix"
    value: ${{ steps.index.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
    - run: index.sh >> "$GITHUB_OUTPUT"
      shell: bash
      id: index
