name: Matrix build
description: "Generate a matrix for building docker images"
inputs:
  images:
    description: "The list of base images to build (separated by comma)"
    required: true
  platforms:
    description: "The list of platforms to build (separated by comma)"
    required: true

outputs:
  matrix:
    description: "Generated strategy.matrix"
    value: ${{ steps.index.outputs.matrix }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: index.sh >> $GITHUB_OUTPUT
      shell: bash
      id: index
