name: Docker setup
description: Prepare docker environment for building images

inputs:
  platforms:
    description: The list of platforms to set up (separated by comma)
    required: true
  dh_username:
    description: Docker Hub username
    required: true
  dh_token:
    description: Docker Hub token
    required: true
  gh_registry:
    description: GitHub Container url
    required: true
  gh_username:
    description: GitHub Container username
    required: true
  gh_token:
    description: GitHub Container token
    required: true

runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      with:
        platforms: ${{ inputs.platforms }}
    - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      with:
        platforms: ${{ inputs.platforms }}
    - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        username: ${{ inputs.dh_username }}
        password: ${{ inputs.dh_token }}
    - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: ${{ inputs.gh_registry }}
        username: ${{ inputs.gh_username }}
        password: ${{ inputs.gh_token }}
