name: Docker setup
description: Prepare docker environment for building images

inputs:
  platforms:
    description: The list of platforms to set up (separated by comma)
    required: true
  dh_username:
    description: Docker Hub username
    required: true
  dh_token:
    description: Docker Hub token
    required: true
  gh_registry:
    description: GitHub Container url
    required: true
  gh_username:
    description: GitHub Container username
    required: true
  gh_token:
    description: GitHub Container token
    required: true

runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      with:
        platforms: ${{ inputs.platforms }}
    - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      with:
        platforms: ${{ inputs.platforms }}
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        username: ${{ inputs.dh_username }}
        password: ${{ inputs.dh_token }}
    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.gh_registry }}
        username: ${{ inputs.gh_username }}
        password: ${{ inputs.gh_token }}
