name: Docker matrix
description: "Generate a matrix for building docker images"
inputs:
  images:
    description: "The list of base images to build (separated by comma)"
    required: true
  platforms:
    description: "The list of platforms to build (separated by comma)"
    required: true

outputs:
  build-matrix:
    description: "Generated strategy.matrix for docker-build job"
    value: ${{ steps.index.outputs.build-matrix }}
  merge-matrix:
    description: "Generated strategy.matrix for docker-merge job"
    value: ${{ steps.index.outputs.merge-matrix }}

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: index.sh
      shell: bash
      id: index
      env:
        INPUT_IMAGES: ${{ inputs.images }}
        INPUT_PLATFORMS: ${{ inputs.platforms }}
