## ref: https://www.chezmoi.io/reference/special-files/chezmoidata-format/
## Prerequisite command
## - zsh - Default shell
## - curl - Install commands in general
## - gpg - Decrypt chezmoi configurations
## - git - For zinit plugin manager
## - file - For starship install command

packages:
  darwin:
    taps:
      - homebrew/bundle
    brews:
      - ca-certificates
      - cloc
      - coreutils
      - curl
      - git
      - mas
      - nmap
      - openssh
    casks:
      - 1password@beta
      - alfred
      - brave-browser
      - docker
      - font-jetbrains-mono
      - font-jetbrains-mono-nerd-font
      - gpg-suite
      - jetbrains-toolbox
      - logi-options+
      - setapp
      - slack
      - visual-studio-code-insiders
      - warp
    mas:
      - id: 424390742
        name: Compressor
      - id: 634159523
        name: MainStage
      - id: 424389933
        name: Final Cut Pro
      - id: 634148309
        name: Logic Pro
      - id: 409183694
        name: Keynote
      - id: 409203825
        name: Numbers
      - id: 409201541
        name: Pages
      - id: 441258766
        name: Magnet
      - id: 497799835
        name: Xcode
  linux:
    apts:
      - gpg
      - curl
      - git
      - zsh
      - file
