## ref: https://www.chezmoi.io/reference/special-files/chezmoidata-format/
## Prerequisite command
## - zsh - Default shell
## - curl - Install commands in general
## - gpg - Decrypt chezmoi configurations
## - git - For zinit plugin manager
## - file - For starship install command

packages:
  darwin:
    taps:
      - homebrew/bundle
    brews:
      - git
      - glib
      - cloc
      - coreutils
      - curl
      - git
      - graphviz
      - nmap
      - openssh
    casks:
      - 1password@beta
      - alfred
      - brave-browser
      - docker
      - font-fira-code-nerd-font
      - font-jetbrains-mono
      - gpg-suite
      - logi-options+
      - miro
      - setapp
      - slack
      - visual-studio-code-insiders
      - warp
  linux:
    apts:
      - gpg
      - curl
      - git
      - zsh
      - file
