## ref: https://www.chezmoi.io/reference/special-files/chezmoidata-format/

packages:
  darwin:
    taps:
      - homebrew/bundle
    brews:
      - git
      - glib
      - cloc
      - coreutils
      - curl
      - git
      - graphviz
      - nmap
      - openssh
    casks:
      - 1password@beta
      - alfred
      - brave-browser
      - docker
      - font-fira-code-nerd-font
      - font-jetbrains-mono
      - gpg-suite
      - logi-options+
      - miro
      - setapp
      - slack
      - visual-studio-code-insiders
      - warp
  linux:
    apts:
      - gpg ## Prerequisite
      - curl ## Prerequisite
      - git ## Prerequisite
      - zsh ## Prerequisite
      - file ## For starship
