## ref: https://www.chezmoi.io/reference/special-files/chezmoidata-format/
## Prerequisite command
## - zsh - Default shell
## - curl - Install commands in general
## - gpg - Decrypt chezmoi configurations
## - git - For zinit plugin manager
## - file - For starship install command

packages:
  darwin:
    taps: []
    brews:
      - ca-certificates
      - cloc
      - coreutils
      - cosign
      - curl
      - git
      - lua
      - luarocks
      - mas ## Mac App Store CLI
      - nmap
      - openssh
      - ykman ## For Yubico Authenticator CLI
    casks:
      - 1password@beta
      - affinity-designer
      - affinity-photo
      - affinity-publisher
      - alfred
      - brave-browser
      - chatgpt
      - claude
      - docker-desktop
      - font-jetbrains-mono
      - font-jetbrains-mono-nerd-font
      - gpg-suite
      - keybase
      - logi-options+
      - setapp
      - slack
      - visual-studio-code-insiders
      - wezterm
    mas:
      - id: 1569813296
        name: 1Password for Safari
      - id: 409183694
        name: Keynote
      - id: 441258766
        name: Magnet
      - id: 409203825
        name: Numbers
      - id: 409201541
        name: Pages
      - id: 497799835
        name: Xcode
      - id: 1497506650
        name: Yubico Authenticator
      - id: 424389933
        name: Final Cut Pro
      # - id: 424390742
      #   name: Compressor
      # - id: 634159523
      #   name: MainStage
      # - id: 634148309
      #   name: Logic Pro
  linux:
    apts:
      - gpg
      - curl
      - git
      - zsh
      - file
      - unzip
      - cloc
