[env]
AWS_PROFILE = "rxco-dev-adm"
KUBECONFIG = "{{env.HOME}}/.kube/works/config.rx"

[tasks.ka]
description = 'Run kubectl with admin permissions'
run = "kubectl --context dev:rx/a"

[tasks.ha]
description = 'Run helm with admin permissions'
run = "helm --kube-context dev:rx/a"

