#:schema https://developers.openai.com/codex/config-schema.json

## https://developers.openai.com/codex/config-reference

approval_policy        = "on-request"
file_opener            = "vscode-insiders"
model                  = "gpt-5.3-codex"
model_reasoning_effort = "high"
personality            = "pragmatic"

[history]
max_bytes   = 5000000    ## 5 MB
persistence = "save-all"

[feedback]
enabled = false

[mcp_servers.context7]
args    = ["exec", "npm:@upstash/context7-mcp", "--", "context7-mcp"]
command = "mise"

[mcp_servers.memory]
args = [
  "exec",
  "npm:@modelcontextprotocol/server-memory",
  "--",
  "mcp-server-memory",
]
command = "mise"

[mcp_servers.sequential-thinking]
command = "mise"
args = [
  "exec",
  "npm:@modelcontextprotocol/server-sequential-thinking",
  "--",
  "mcp-server-sequential-thinking",
]

[mcp_servers.svelte]
url = "https://mcp.svelte.dev/mcp"
