name: Main

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  INSTALL_CLI: /tmp/chezmoi.sh
  CHEZMOI_BIN: /tmp/bin

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up chezmoi
        uses: ./.github/actions/setup-chezmoi
      - name: Apply chezmoi config
        run: |
          chezmoi init --one-shot --promptDefaults \
            --source ${{ github.workspace }}
      - name: Run full setup
        run: kdf-setup.sh
      - name: Verify the setup
        run: kdf-verify.sh
