name: Main

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  INSTALL_CLI: /tmp/chezmoi.sh
  CHEZMOI_BIN: /tmp/bin

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up chezmoi
        uses: ./.github/actions/setup-chezmoi
      - name: Apply chezmoi config
        run: |
          chezmoi init --one-shot --promptDefaults \
            --source ${{ github.workspace }}
      - name: Run full setup
        run: kdf-setup.sh
      - name: Verify the setup
        run: kdf-verify.sh
