name: Main

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  INSTALL_CLI: /tmp/chezmoi.sh
  CHEZMOI_BIN: /tmp/bin

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up chezmoi
        uses: ./.github/actions/setup-chezmoi
      - name: Apply chezmoi config
        run: |
          chezmoi init --apply \
            --force --purge-binary \
            --promptDefaults \
            --source ${{ github.workspace }}
      - name: Run full dotfiles
        run: kdf-setup-full.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHEZMOI_SOURCE: ${{ github.workspace }}
          CHEZMOI_KEY_TXT_BASE64: ${{ secrets.CHEZMOI_KEY_TXT_BASE64 }}
      - name: Verify dotfiles
        run: kdf-verify.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHEZMOI_SOURCE: ${{ github.workspace }}
      - name: Clean up dotfiles
        if: ${{ always() }}
        run: kdf-cleanup.sh
        env:
          CHEZMOI_SOURCE: ${{ github.workspace }}
  try:
    runs-on: ubuntu-latest
    env:
      INSTALL_SCRIPTS: /tmp/brew.sh
    steps:
      - run: curl -fsSLo $INSTALL_SCRIPTS https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
      - run: bash "$INSTALL_SCRIPTS"
      - run: brew install git
